SSO_ENABLED = false
SSO_SERVICE_NAME = 'name'
SSO_SERVICE_PASSWORD = 'pw'
SSO_REDIRECT_URL = 'url'
STUDENT_SSO_REDIRECT_URL = 'redirect'
STUDENT_SSO_SERVICE_NAME = 'name_2'
STUDENT_SSO_SERVICE_PASSWORD = 'pw_2'

