ActsAsFerret::define_index('shared_page',
  :models =>{
      Page => {:fields => [ :sect_num, 
                            :course_name,
                            :term,:year,
                            :course_num,
                            :page_description,
                            :tag_list,
                            :index_subjects_name, 
                            :index_subjects_code,
                            :index_tab_name]}
  }

)

ActsAsFerret::define_index('shared_guide',
  :models =>{
      Guide => {:fields => [:guide_name, 
                            :description,
                            :tag_list, 
                            :index_masters, 
                            :index_subjects_name, 
                            :index_subjects_code,
                            :index_tab_name]}
    
  }
)
ActsAsFerret::define_index('shared_tutorial',
  :models =>{
      Tutorial => {:fields => [:name, 
                            :description,
                            :tag_list, 
                            :course_num, 
                            :section_num, 
                            :index_unit_title,
                            :index_unit_slug]}
  }
)
ActsAsFerret::define_index('shared',
  :models =>{
     BookResource  => {:fields => [:module_title, 
                                      :label ,
                                      :tag_list, 
                                      :information , 
                                      :slug,
                                      :published ]},
     CourseWidget  => {:fields => [:module_title, 
                                      :label ,
                                      :tag_list, 
                                      :information , 
                                      :slug,
                                      :published ]},
     CommentResource  => {:fields => [:module_title, 
                                      :label ,
                                      :tag_list, 
                                      :topic , 
                                      :slug,
                                      :published ]},
     DatabaseResource => {:fields => [:module_title ,
                                      :label ,
                                      :tag_list ,
                                      :info , 
                                      :slug,
                                      :published]},
     ImageResource => {:fields => [:module_title ,
                                  :label ,
                                  :tag_list,
                                  :information , 
                                  :slug ,
                                  :published ]},
     InstResource => {:fields => [:module_title,
                                  :label ,
                                  :tag_list ,
                                  :slug ,
                                  :published]},
     LibResource => {:fields => [:module_title ,
                                :label ,
                                :tag_list ,
                                :image_info , 
                                 :slug ,
                                 :published ]},
     MiscellaneousResource => {:fields => [:module_title ,
                                          :label ,
                                          :tag_list ,
                                          :more_info , 
                                          :slug ,
                                          :published ]},
     QuizResource => {:fields => [:module_title ,
                                  :label ,
                                  :tag_list ,
                                  :description , 
                                  :slug ,
                                  :published ]},
     ReserveResource => {:fields => [:module_title ,
                                  :label ,
                                  :tag_list ,
                                  :reserves , 
                                  :slug ,
                                  :published ]},                                  
     RssResource => {:fields => [:module_title ,
                                :label ,
                                :tag_list,
                                :information ,
                                :topic , 
                                :slug,
                                :published ]},
     UploaderResource => {:fields => [:module_title ,
                                 :label,
                                 :tag_list ,
                                 :info , 
                                 :slug ,
                                 :published ]},
     UrlResource => {:fields => [:module_title ,
                                 :label,
                                 :tag_list ,
                                 :information , 
                                 :slug ,
                                 :published ]},
     VideoResource => {:fields => [:module_title ,
                                   :label ,
                                   :tag_list ,
                                   :information, 
                                   :slug ,
                                   :published ]} 
  }
 ) 